### ISSUE TITLE
[Feature Request] BehaviorScripts

### ISSUE THREAD

**Issue by bluisblu** [Brawmario/libsm64-godot#13]
Would be neat to be able to apply them to objects like you can with the surface properties, although I assume this is a limitation with libsm64 because I can't find them being implemented there, so I'm not sure if it's actually possible.

**Comment by Brawmario** [comment]
I'm not aware of what BehaviorScripts are, but references to it seem to be scrubbed from libsm64. If they were to be implemented in libsm64 I could exposed them in this addon.

**Comment by bluisblu** [comment]
Ah that's unfortunate, maybe there's another way of implementing these on my end, but here's what I was talking about:
https://github.com/n64decomp/sm64/tree/9921382a68bb0c865e5e45eb594d9c64db59b1af/src/game/behaviors
https://github.com/n64decomp/sm64/blob/9921382a68bb0c865e5e45eb594d9c64db59b1af/data/behavior_data.c
https://github.com/n64decomp/sm64/blob/9921382a68bb0c865e5e45eb594d9c64db59b1af/src/engine/behavior_script.c

Edit: Looks like it's macros that communicate directly with n64 hardware...

Edit 2: And yeah behavior-reliant code was commented out in libsm64:
https://github.com/libsm64/libsm64/blob/9a98ffbb865c48bfbc04c2c87d2d82a255bd46b2/src/decomp/game/interaction.c#L128

**Comment by bluisblu** [comment]
In retrospect the behavior of objects in the world should be implemented by users of the addon, not the addon itself
