### ISSUE TITLE
Extensibility questions

### ISSUE THREAD

**Issue by nightblade9** [Brawmario/libsm64-godot#14]
Hi,

Is this project still under development?

I have a few ideas I an thinking of making, but I need some clarification on what is and isn't possible, given that a lot of behaviour isn't in gdscript. I looked through all the extension and addon code, but couldn't figure it out.

1) Is there any way to override behaviours to do something else? E.g. pressing B doesn't punch, and/or executes my custom code. I see an action signal in Mario's class, but no way to interrupt existing behaviour.

2) is it possible to change Mario's behaviour, selectively or entirely? Maybe recolour red to blue, or something simple like like adding a modulate color.

3) Is there any way to get different instances of Mario to react to different gamepads?

**Comment by Brawmario** [comment]
Hello!

I'm not actively working on the addon, it's feature complete for me at least. I could work on more stuff if there's demand for it tho.

1. I'm not sure what you mean by this. Did you remember to set the Input Action Names for the Mario node instance?
2.  Not sure what changing color has to do with behaviour, but I don't think you would be able to do that, since Mario's 3D mesh is rebuild every frame. Maybe I should expose an extra pass material to allow for that.
3. Of course! You just need to set each Mario instance to react to diferent Input Actions.

**Comment by nightblade9** [comment]
Great, thank you for the answers.

For 1. Let's say I have a switch in my game, and I want Mario to press B to activate it. Is there any way to do this? I could connect to the signal on the Mario mesh and react to the button, but is there any way to stop him from punching?

For 2. I'm thinking of making a couch co-op game where each player controls a different instance of Mario. It would be helpful to be able to recolour him somehow.

**Comment by nightblade9** [comment]
Hi again, still hoping to get some answers. Might be useful to put together a sample of stuff, maybe I can do it.

1. How do i create an object that reacts to a certain Mario behaviour, like being punched or stomped?

2. Can i freeze/disable Mario's controls at runtime? I want to make a platform that, when jumped on, freezes Mario and the platform moves to your input instead.

**Comment by nightblade9** [comment]
One issue I see: there's no way to detect a collision. 

Let's say I want to create a coin, and when it's touched by Mario, it disappears. Right now, that's impossible; even though the editor shows the `SM64Mario` node under `CharacterBody3D`, it doesn't trigger any of the `Area3D` functions.

![image](https://github.com/Brawmario/libsm64-godot/assets/31222662/1bc56763-0431-481a-8917-880292ef0fb2)

Repro steps:

- Create an Area3D with a `CollisionShape3D` with a big polygon
- Wire up events for `area_entered`, `body_entered`, and `area_shape_entered`
- In all three events, print out whatever it is that's passed in as the parameter
- Play around. No matter what Mario does, none of those events are ever triggered.

**Comment by nightblade9** [comment]
Okay, so I solved this. I saw your comment elsewhere about adding an area to Mario. That works, but I can't figure out what the best shape is, and the best size. In the demo code, you set Mario's scale to 75. Since I can't see the mesh in-editor, how do I figure out the best-fit collision shape?

**Comment by nightblade9** [comment]
Sorry about all the message spam. I deleted all my comments. I got almost everything working as expected.

Cheers and thanks for the good work!
