### ISSUE TITLE
plugin not properly detecting ROM

### ISSUE THREAD

**Issue by Gapva** [Brawmario/libsm64-godot#2]
a fresh, untouched ROM of SM64 (or any SM64 rom, untouched or not) doesn't work as of 11/3/2022 on Godot 4 - Beta 3.

in the example project, the integrated filesystem tells me i have an "invalid or corrupt" ROM.

**Comment by Brawmario** [comment]
Thanks for submitting an issue!

What is the the SHA256 of the ROM you are trying to use? For safety reasons the example project checks against the known hash of a valid Super Mario 64 (USA) ROM, it being:

>17ce077343c6133f8c9f2d6d6d9a4ab62c8cd2aa57c40aea1f490b4c8bb21d9117ce077343c6133f8c9f2d6d6d9a4ab62c8cd2aa57c40aea1f490b4c8bb21d91

The check is done in the `demo/main.gd` file. Does removing the check makes the project work with the ROMs you're trying to use?

**Comment by Gapva** [comment]
I am currently not home right now, so I can't find that information yet; but the thing is, when I submit my ROM to the exported example build, it works perfectly. it just doesn't work in the editor though, so it can't be an issue with my rom.

removing the checks also do not work

I had already read through the project source for the control scene, but to no avail

do you think a godot update might have broken a few checks?

**Comment by Brawmario** [comment]
Are trying to use Godot 4 beta 4? Something definitely broke with this update, trying to figure out what might have changed (Unfortunately there's still no comprehensive change list for it).

At what point in the project does it fail? I'd like to look at a screenshot of the problem.

**Comment by Gapva** [comment]
I'm using beta 3.

the project doesn't technically "error" at all, it just tells me I have an invalid rom when I try to run the example project in the editor, rather than the executable.

if I get rid of the checks, mario just doesn't spawn, but I can still control the camera.

I'll get a screenshot as soon as I can ! (sometime after 4PM EST probably)

* I should also mention that this doesn't work in a new project either, assigning the ROM (.z64) to a SM64Handler doesn't really do anything.

**Comment by Brawmario** [comment]
I just released a new version changing a bit how the file is selected, instead of getting the `current_path` property of the file picker it uses the `file_selected` signal (for some reason the `current_path` property doesn't include the disk drive letter on Windows).

I forgot to ask, what OS are you using? I haven't been able to test the Linux builds yet.

**Comment by Gapva** [comment]
thank you for your efforts to rid my issues. I'm on win10. when I get home, I'll let you know how it goes. 😄

**Comment by Gapva** [comment]
AWESOME !! everything works as expected with the new beta 4 release. thank you so much, brawmario!
