### ISSUE TITLE
Vanish Cap not working still

### ISSUE THREAD

**Issue by bluisblu** [Brawmario/libsm64-godot#21]
I tried applying a SurfacePropertiesComponent to a wall in the mini_level scene with the `Vanish Cap Walls` property, and giving mario the vanish cap in the `create` function of `sm64_mario.gd` like so:

```gd
func create() -> void:
	if SM64Global.is_init():
		if _id >= 0:
			delete()
		_id = _internal.mario_create(global_position, global_rotation)
		if _id < 0:
			return
		
		_internal.interact_cap(SM64Mario.Caps.VANISH)
#...
```

However as of 1.4.0 I am still unable to pass through the wall. Have not tested it in plain libsm64, not sure if the fix on that end didn't work or if it just doesn't work in godot, or if I'm just doing something wrong.

Edit: I guess I could've just changed the `start_cap` in `initial_scenario.gd` lol, still doesn't work though

**Comment by Brawmario** [comment]
Yup, I tried it myself and it doesn't seem to work, I'll take a look at it. Funny thing is, the code that dealt with Vanish Walls was in fact missing in `libsm64` a while ago, and I personally restored it :P. I confess I didn't test it in pure `libsm64` either, but it didn't seem like it shouldn't have worked.

**Comment by bluisblu** [comment]
No worries! I changed my name since but I was also the one who made the issue on the `libsm64` end a while back, but my real hope was for it to start working here lol

**Comment by Brawmario** [comment]
Alright, my latest commit 2b9fc487727094750b59745118b933c7746459db should fix this. The collision with `Vanish Cap Walls` is indeed working in `libsm64`, however I was incorrectly defining the editor hint, so the values set misaligned, lol. I'll release a new version hopefully tomorrow.
