### ISSUE TITLE
Godot 3 Feature Backporting

### ISSUE THREAD

**Issue by gizmogoat** [Brawmario/libsm64-godot#22]
Hi! Thanks for taking your time reading this :)

Is there a chance any of the features from the master branch will ever be backported into godot3? I wish to mod Mario into a godot3 game via a relatively new mod loader and game, and I'm currently in the process of making that, but it's lacking some features (audio support in particular would be nice to have)

It's kinda puzzling the original developer didn't use Godot 4 in the first place since the game only released a month or two ago, but hey what do I know

I totally understand if this is not a priority to you and Godot 4 is definitely the way to go for new projects based upon these bindings.

Thank you again!

**Comment by Brawmario** [comment]
Hello, thanks for showing interest in the project!

Unfortunately, the current project is basically a completely different beast from when I made the last Godot 3 version. I basically made a complete refactor of the internals and the exposed API itself. A Godot 3 backport would basically have to be a "downgrade" of the master branch made from scratch, and I don't think there's a straightforward way to convert a Godot 4 project backwards into a Godot 3 project. As it stands, it would take far too much time and effort to make a new Godot 3 version. Thank you for reaching out nonetheless.

**Comment by gizmogoat** [comment]
> Hello, thanks for showing interest in the project!
> 
> Unfortunately, the current project is basically a completely different beast from when I made the last Godot 3 version. I basically made a complete refactor of the internals and the exposed API itself. A Godot 3 backport would basically have to be a "downgrade" of the master branch made from scratch, and I don't think there's a straightforward way to convert a Godot 4 project backwards into a Godot 3 project. As it stands, it would take far too much time and effort to make a new Godot 3 version. Thank you for reaching out nonetheless.

That sucks :(

I totally understand though - I figured it would be a situation like this where it would be a large task to rework large portions of the implementation to downgrade for Godot 3. 

Maybe someday, someone will contribute/fork and make a Godot 3 version based upon the newer code (or just branch off from Godot 3 and make everything from the beginning forward)

The developer has shown some minor interest in porting to Godot 4 in the future, so maybe in a year's time or so I'll either have an improved Godot 3 version of this project, or the game I wish to mod gets ported to Godot 4 from 3.5.

Thanks again!
